CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA IF NOT EXISTS honcho;
CREATE TABLE honcho.active_queue_sessions (
    last_updated timestamp with time zone DEFAULT now() NOT NULL,
    id text NOT NULL,
    work_unit_key text NOT NULL
);
CREATE TABLE honcho.alembic_version (
    version_num character varying(32) NOT NULL
);
CREATE TABLE honcho.collections (
    id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    workspace_name text NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    observer text NOT NULL,
    observed text NOT NULL,
    CONSTRAINT ck_collections_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_collections_id_length CHECK ((length(id) = 21)),
    CONSTRAINT ck_collections_public_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_collections_public_id_length CHECK ((length(id) = 21))
);
CREATE TABLE honcho.documents (
    id text NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    content text NOT NULL,
    embedding public.vector(1536),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    workspace_name text NOT NULL,
    session_name text,
    observer text NOT NULL,
    observed text NOT NULL,
    level text DEFAULT 'explicit'::text NOT NULL,
    times_derived integer DEFAULT 1 NOT NULL,
    source_ids jsonb,
    deleted_at timestamp with time zone,
    sync_state text DEFAULT 'pending'::text NOT NULL,
    last_sync_at timestamp with time zone,
    sync_attempts integer DEFAULT 0 NOT NULL,
    CONSTRAINT ck_documents_content_length CHECK ((length(content) <= 65535)),
    CONSTRAINT ck_documents_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_documents_id_length CHECK ((length(id) = 21)),
    CONSTRAINT ck_documents_public_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_documents_public_id_length CHECK ((length(id) = 21))
);
CREATE TABLE honcho.message_embeddings (
    id bigint NOT NULL,
    content text NOT NULL,
    embedding public.vector(1536),
    message_id text NOT NULL,
    workspace_name text NOT NULL,
    session_name text NOT NULL,
    peer_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    sync_state text DEFAULT 'pending'::text NOT NULL,
    last_sync_at timestamp with time zone,
    sync_attempts integer DEFAULT 0 NOT NULL
);
ALTER TABLE honcho.message_embeddings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME honcho.message_embeddings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE honcho.messages (
    id bigint NOT NULL,
    public_id text NOT NULL,
    content text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    peer_name text NOT NULL,
    workspace_name text NOT NULL,
    session_name text NOT NULL,
    token_count integer DEFAULT 0 NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    seq_in_session bigint NOT NULL,
    CONSTRAINT ck_messages_content_length CHECK ((length(content) <= 65535)),
    CONSTRAINT ck_messages_public_id_format CHECK ((public_id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_messages_public_id_length CHECK ((length(public_id) = 21))
);
ALTER TABLE honcho.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME honcho.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE honcho.peers (
    id text NOT NULL,
    name text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    configuration jsonb DEFAULT '{}'::jsonb NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    workspace_name text NOT NULL,
    CONSTRAINT ck_peers_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_peers_id_length CHECK ((length(id) = 21)),
    CONSTRAINT ck_users_name_length CHECK ((length(name) <= 512)),
    CONSTRAINT ck_users_public_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_users_public_id_length CHECK ((length(id) = 21))
);
CREATE TABLE honcho.queue (
    id bigint NOT NULL,
    session_id text,
    payload jsonb NOT NULL,
    processed boolean DEFAULT false NOT NULL,
    task_type text NOT NULL,
    work_unit_key text NOT NULL,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    workspace_name text,
    message_id bigint
);
ALTER TABLE honcho.queue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME honcho.queue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE honcho.session_peers (
    workspace_name text NOT NULL,
    session_name text NOT NULL,
    peer_name text NOT NULL,
    configuration jsonb DEFAULT '{}'::jsonb NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    joined_at timestamp with time zone DEFAULT now() NOT NULL,
    left_at timestamp with time zone
);
CREATE TABLE honcho.sessions (
    id text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    configuration jsonb DEFAULT '{}'::jsonb NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    workspace_name text NOT NULL,
    name text NOT NULL,
    CONSTRAINT ck_sessions_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_sessions_id_length CHECK ((length(id) = 21)),
    CONSTRAINT ck_sessions_name_length CHECK ((length(name) <= 512)),
    CONSTRAINT ck_sessions_public_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_sessions_public_id_length CHECK ((length(id) = 21))
);
CREATE TABLE honcho.webhook_endpoints (
    id text NOT NULL,
    workspace_name text NOT NULL,
    url text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_webhook_endpoints_webhook_endpoint_url_length CHECK ((length(url) <= 2048))
);
CREATE TABLE honcho.workspaces (
    id text NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    configuration jsonb DEFAULT '{}'::jsonb NOT NULL,
    internal_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT ck_apps_name_length CHECK ((length(name) <= 512)),
    CONSTRAINT ck_apps_public_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_apps_public_id_length CHECK ((length(id) = 21)),
    CONSTRAINT ck_workspaces_id_format CHECK ((id ~ '^[A-Za-z0-9_-]+$'::text)),
    CONSTRAINT ck_workspaces_id_length CHECK ((length(id) = 21))
);
ALTER TABLE ONLY honcho.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);
ALTER TABLE ONLY honcho.active_queue_sessions
    ADD CONSTRAINT pk_active_queue_sessions PRIMARY KEY (id);
ALTER TABLE ONLY honcho.collections
    ADD CONSTRAINT pk_collections PRIMARY KEY (id);
ALTER TABLE ONLY honcho.documents
    ADD CONSTRAINT pk_documents PRIMARY KEY (id);
ALTER TABLE ONLY honcho.message_embeddings
    ADD CONSTRAINT pk_message_embeddings PRIMARY KEY (id);
ALTER TABLE ONLY honcho.messages
    ADD CONSTRAINT pk_messages PRIMARY KEY (id);
ALTER TABLE ONLY honcho.peers
    ADD CONSTRAINT pk_peers PRIMARY KEY (id);
ALTER TABLE ONLY honcho.queue
    ADD CONSTRAINT pk_queue PRIMARY KEY (id);
ALTER TABLE ONLY honcho.session_peers
    ADD CONSTRAINT pk_session_peers PRIMARY KEY (workspace_name, session_name, peer_name);
ALTER TABLE ONLY honcho.sessions
    ADD CONSTRAINT pk_sessions PRIMARY KEY (id);
ALTER TABLE ONLY honcho.webhook_endpoints
    ADD CONSTRAINT pk_webhook_endpoints PRIMARY KEY (id);
ALTER TABLE ONLY honcho.workspaces
    ADD CONSTRAINT pk_workspaces PRIMARY KEY (id);
ALTER TABLE ONLY honcho.active_queue_sessions
    ADD CONSTRAINT uq_active_queue_sessions_work_unit_key UNIQUE (work_unit_key);
ALTER TABLE ONLY honcho.collections
    ADD CONSTRAINT uq_collections_observer_observed_workspace_name UNIQUE (observer, observed, workspace_name);
ALTER TABLE ONLY honcho.messages
    ADD CONSTRAINT uq_messages_public_id UNIQUE (public_id);
ALTER TABLE ONLY honcho.messages
    ADD CONSTRAINT uq_messages_workspace_name_session_name_seq_in_session UNIQUE (workspace_name, session_name, seq_in_session);
ALTER TABLE ONLY honcho.peers
    ADD CONSTRAINT uq_peers_name_workspace_name UNIQUE (name, workspace_name);
ALTER TABLE ONLY honcho.sessions
    ADD CONSTRAINT uq_sessions_name_workspace_name UNIQUE (name, workspace_name);
ALTER TABLE ONLY honcho.workspaces
    ADD CONSTRAINT uq_workspaces_name UNIQUE (name);
CREATE INDEX ix_collections_created_at ON honcho.collections USING btree (created_at);
CREATE INDEX ix_collections_observed ON honcho.collections USING btree (observed);
CREATE INDEX ix_collections_observer ON honcho.collections USING btree (observer);
CREATE INDEX ix_collections_workspace_name ON honcho.collections USING btree (workspace_name);
CREATE INDEX ix_documents_created_at ON honcho.documents USING btree (created_at);
CREATE INDEX ix_documents_deleted_at ON honcho.documents USING btree (deleted_at) WHERE (deleted_at IS NOT NULL);
CREATE INDEX ix_documents_embedding_hnsw ON honcho.documents USING hnsw (embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX ix_documents_observed ON honcho.documents USING btree (observed);
CREATE INDEX ix_documents_observer ON honcho.documents USING btree (observer);
CREATE INDEX ix_documents_session_name ON honcho.documents USING btree (session_name);
CREATE INDEX ix_documents_source_ids_gin ON honcho.documents USING gin (source_ids);
CREATE INDEX ix_documents_sync_state ON honcho.documents USING btree (sync_state);
CREATE INDEX ix_documents_sync_state_last_sync_at ON honcho.documents USING btree (sync_state, last_sync_at);
CREATE INDEX ix_documents_workspace_name ON honcho.documents USING btree (workspace_name);
CREATE INDEX ix_message_embeddings_created_at ON honcho.message_embeddings USING btree (created_at);
CREATE INDEX ix_message_embeddings_embedding_hnsw ON honcho.message_embeddings USING hnsw (embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX ix_message_embeddings_message_id ON honcho.message_embeddings USING btree (message_id);
CREATE INDEX ix_message_embeddings_peer_name ON honcho.message_embeddings USING btree (peer_name);
CREATE INDEX ix_message_embeddings_session_name ON honcho.message_embeddings USING btree (session_name);
CREATE INDEX ix_message_embeddings_sync_state ON honcho.message_embeddings USING btree (sync_state);
CREATE INDEX ix_message_embeddings_sync_state_last_sync_at ON honcho.message_embeddings USING btree (sync_state, last_sync_at);
CREATE INDEX ix_message_embeddings_workspace_name ON honcho.message_embeddings USING btree (workspace_name);
CREATE INDEX ix_messages_content_gin ON honcho.messages USING gin (to_tsvector('english'::regconfig, content));
CREATE INDEX ix_messages_created_at ON honcho.messages USING btree (created_at);
CREATE INDEX ix_messages_peer_name ON honcho.messages USING btree (peer_name);
CREATE INDEX ix_messages_session_lookup ON honcho.messages USING btree (session_name, id) INCLUDE (id, created_at);
CREATE INDEX ix_messages_workspace_name ON honcho.messages USING btree (workspace_name);
CREATE INDEX ix_peers_created_at ON honcho.peers USING btree (created_at);
CREATE INDEX ix_peers_workspace_name ON honcho.peers USING btree (workspace_name);
CREATE INDEX ix_queue_created_at ON honcho.queue USING btree (created_at);
CREATE INDEX ix_queue_message_id_not_null ON honcho.queue USING btree (message_id) WHERE (message_id IS NOT NULL);
CREATE INDEX ix_queue_processed ON honcho.queue USING btree (processed);
CREATE INDEX ix_queue_session_id ON honcho.queue USING btree (session_id);
CREATE INDEX ix_queue_work_unit_key_processed_id ON honcho.queue USING btree (work_unit_key, processed, id);
CREATE INDEX ix_queue_workspace_name ON honcho.queue USING btree (workspace_name);
CREATE INDEX ix_sessions_created_at ON honcho.sessions USING btree (created_at);
CREATE INDEX ix_sessions_workspace_name ON honcho.sessions USING btree (workspace_name);
CREATE INDEX ix_webhook_endpoints_workspace_name ON honcho.webhook_endpoints USING btree (workspace_name);
CREATE INDEX ix_workspaces_created_at ON honcho.workspaces USING btree (created_at);
CREATE UNIQUE INDEX uq_queue_dream_pending_work_unit_key ON honcho.queue USING btree (work_unit_key) WHERE ((task_type = 'dream'::text) AND (processed = false));
CREATE UNIQUE INDEX uq_queue_reconciler_pending_work_unit_key ON honcho.queue USING btree (work_unit_key) WHERE ((task_type = 'reconciler'::text) AND (processed = false));
ALTER TABLE ONLY honcho.collections
    ADD CONSTRAINT fk_collections_observed_workspace_name_peers FOREIGN KEY (observed, workspace_name) REFERENCES honcho.peers(name, workspace_name);
ALTER TABLE ONLY honcho.collections
    ADD CONSTRAINT fk_collections_observer_workspace_name_peers FOREIGN KEY (observer, workspace_name) REFERENCES honcho.peers(name, workspace_name);
ALTER TABLE ONLY honcho.collections
    ADD CONSTRAINT fk_collections_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES honcho.workspaces(name);
ALTER TABLE ONLY honcho.documents
    ADD CONSTRAINT fk_documents_observed_workspace_name_peers FOREIGN KEY (observed, workspace_name) REFERENCES honcho.peers(name, workspace_name);
ALTER TABLE ONLY honcho.documents
    ADD CONSTRAINT fk_documents_observer_observed_workspace_name_collections FOREIGN KEY (observer, observed, workspace_name) REFERENCES honcho.collections(observer, observed, workspace_name);
ALTER TABLE ONLY honcho.documents
    ADD CONSTRAINT fk_documents_observer_workspace_name_peers FOREIGN KEY (observer, workspace_name) REFERENCES honcho.peers(name, workspace_name);
ALTER TABLE ONLY honcho.documents
    ADD CONSTRAINT fk_documents_session_workspace FOREIGN KEY (session_name, workspace_name) REFERENCES honcho.sessions(name, workspace_name);
ALTER TABLE ONLY honcho.documents
    ADD CONSTRAINT fk_documents_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES honcho.workspaces(name);
ALTER TABLE ONLY honcho.message_embeddings
    ADD CONSTRAINT fk_message_embeddings_message_id_messages FOREIGN KEY (message_id) REFERENCES honcho.messages(public_id) ON DELETE CASCADE;
ALTER TABLE ONLY honcho.message_embeddings
    ADD CONSTRAINT fk_message_embeddings_peer_name_workspace_name_peers FOREIGN KEY (peer_name, workspace_name) REFERENCES honcho.peers(name, workspace_name);
ALTER TABLE ONLY honcho.message_embeddings
    ADD CONSTRAINT fk_message_embeddings_session_name_workspace_name_sessions FOREIGN KEY (session_name, workspace_name) REFERENCES honcho.sessions(name, workspace_name);
ALTER TABLE ONLY honcho.message_embeddings
    ADD CONSTRAINT fk_message_embeddings_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES honcho.workspaces(name);
ALTER TABLE ONLY honcho.messages
    ADD CONSTRAINT fk_messages_peer_name_peers FOREIGN KEY (peer_name, workspace_name) REFERENCES honcho.peers(name, workspace_name);
ALTER TABLE ONLY honcho.messages
    ADD CONSTRAINT fk_messages_session_name_sessions FOREIGN KEY (session_name, workspace_name) REFERENCES honcho.sessions(name, workspace_name);
ALTER TABLE ONLY honcho.peers
    ADD CONSTRAINT fk_peers_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES honcho.workspaces(name);
ALTER TABLE ONLY honcho.queue
    ADD CONSTRAINT fk_queue_message_id FOREIGN KEY (message_id) REFERENCES honcho.messages(id);
ALTER TABLE ONLY honcho.queue
    ADD CONSTRAINT fk_queue_session_id FOREIGN KEY (session_id) REFERENCES honcho.sessions(id);
ALTER TABLE ONLY honcho.queue
    ADD CONSTRAINT fk_queue_workspace_name FOREIGN KEY (workspace_name) REFERENCES honcho.workspaces(name);
ALTER TABLE ONLY honcho.session_peers
    ADD CONSTRAINT fk_session_peers_peer_name_workspace_name_peers FOREIGN KEY (peer_name, workspace_name) REFERENCES honcho.peers(name, workspace_name);
ALTER TABLE ONLY honcho.session_peers
    ADD CONSTRAINT fk_session_peers_session_name_workspace_name_sessions FOREIGN KEY (session_name, workspace_name) REFERENCES honcho.sessions(name, workspace_name);
ALTER TABLE ONLY honcho.session_peers
    ADD CONSTRAINT fk_session_peers_workspace_name FOREIGN KEY (workspace_name) REFERENCES honcho.workspaces(name);
ALTER TABLE ONLY honcho.sessions
    ADD CONSTRAINT fk_sessions_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES honcho.workspaces(name);
ALTER TABLE ONLY honcho.webhook_endpoints
    ADD CONSTRAINT fk_webhook_endpoints_workspace_name_workspaces FOREIGN KEY (workspace_name) REFERENCES honcho.workspaces(name);
